services:
  api:
    build: .
    container_name: nestJS-${NETWORK_NAME}
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - default_net
      - traefik
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik

      - traefik.http.routers.${NETWORK_NAME}-http.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.${NETWORK_NAME}-http.entrypoints=web
      - traefik.http.middlewares.${NETWORK_NAME}-redir.redirectscheme.scheme=https
      - traefik.http.middlewares.${NETWORK_NAME}-redir.redirectscheme.permanent=true
      - traefik.http.routers.${NETWORK_NAME}-http.middlewares=${NETWORK_NAME}-redir@docker

      - traefik.http.routers.${NETWORK_NAME}.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.${NETWORK_NAME}.entrypoints=websecure
      - traefik.http.routers.${NETWORK_NAME}.tls.certresolver=myresolver

      - traefik.http.services.${NETWORK_NAME}-svc.loadbalancer.server.port=80

networks:
  default_net:
    name: ${NETWORK_NAME}
    driver: bridge
  traefik:
    external: true