name: Deploy DSI Scraper Tracker API

on:
    push:
        branches:
            - master

env: 
    NETWORK_NAME: ${{ vars.NETWORK_NAME }}
    DOMAIN: ${{ vars.DOMAIN }}
    
jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and Deploy with Docker Compose
        run: |
          docker compose down
          docker compose build --no-cache
          docker compose up -d

      - name: Run pending migrations
        run: |
          docker compose run --rm api npx mikro-orm migration:up