name: Deploy DSI Scraper Tracker API - Test

on:
    push:
        branches:
            - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Create .env file from GitHub Secrets
        run: |
            echo "NODE_ENV=${{ vars.NODE_ENV }}" >> .env
            echo "PORT=${{ vars.PORT }}" >> .env
            echo "DB_HOST=${{ vars.DB_HOST }}" >> .env
            echo "DB_PORT=${{ vars.DB_PORT }}" >> .env
            echo "DB_NAME=${{ vars.DB_NAME }}" >> .env
            echo "DB_USER=${{ vars.DB_USER }}" >> .env
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
            echo "API_URL=${{ vars.API_URL }}" >> .env
            echo "NETWORK_NAME=${{ vars.NETWORK_NAME }}" >> .env
            echo "DOMAIN=${{ vars.DOMAIN }}" >> .env
        
      - name: Build and Deploy with Docker Compose
        run: |
          docker compose down
          docker compose build --no-cache
          docker compose up -d