name: Deploy DSI Scraper Tracker API

on:
    push:
        branches:
            - master

jobs:
  deploy:
    runs-on: self-hosted

    env:
      NODE_ENV: ${{ vars.NODE_ENV }}
      PORT: ${{ vars.PORT }}
      DB_HOST: ${{ vars.DB_HOST }}
      DB_PORT: ${{ vars.DB_PORT }}
      DB_NAME: ${{ vars.DB_NAME }}
      DB_USER: ${{ vars.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      API_URL: ${{ vars.API_URL }}
      NETWORK_NAME: ${{ vars.NETWORK_NAME }}
      DOMAIN: ${{ vars.DOMAIN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Create .env file from GitHub Secrets
        run: |
          cat <<EOF > .env
          NODE_ENV=$NODE_ENV
          PORT=$PORT
          DB_HOST=$DB_HOST
          DB_PORT=$DB_PORT
          DB_NAME=$DB_NAME
          DB_USER=$DB_USER
          DB_PASSWORD=$DB_PASSWORD
          API_URL=$API_URL
          NETWORK_NAME=$NETWORK_NAME
          DOMAIN=$DOMAIN
          EOF

      - name: Run MikroORM Migrations
        run: docker compose run --rm api npm run migration:up

      - name: Pull & Restart Docker stack
        run: |
          set -e
          docker compose pull
          docker compose up -d --remove-orphans
          docker image prune -f